AWSTemplateFormatVersion: 2010-09-09

Description: ECS Infrastructure Interview Template 1

Transform: AWS::Serverless-2016-10-31

Parameters:

  pArtifactS3BucketName:
    Description: Name of the S3 bucket for storing source code
    Type: String

  pArtifactS3Key:
    Description: Source code key for the artifact in S3 bucket
    Type: String

  pFunctionAliasName:
    Description: Alias name for lambda function
    Type: String

  pLogLevel:
    Description: Verbosity level for logging
    Type: String
    Default: Info
    AllowedValues:
      - Info
      - Warning
      - Error
      - Debug
      - Critical

  pSSMPrefix:
    Description: SSM Parameter prefix name
    Type: String

Resources:
  rLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Name: lambda-function-role
      Path: /
      Policies:
        - PolicyName: allow-ec2
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
                - ec2:*
              Effect: Allow
              Resource: '*'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
        - arn:aws:iam::aws:policy/AmazonGlacierFullAccess

  rLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.lambda_handler
      Environment:
        Variables:
          LOG_LEVEL: !Ref pLogLevel
      CodeUri:
        Bucket: !Ref pArtifactS3BucketName
        Key: !Ref pArtifactS3Key
      Role: !Ref rLambdaFunctionRole
      AutoPublishAlias: !Ref pFunctionAliasName
      DeploymentPreference:
        Type: AllAtOnce
      Alarms:
        - !Ref rLambdaFunctionAliasErrorAlarm
        - !Ref rLambdaFunctionVersionErrorAlarm

  rLambdaArnSSMParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Description: !Sub '${AWS::StackName} Lambda Arn'
      Name: !Sub '/${pSSMPrefix}/LambdaArn'
      Type: String
      Value: !GetAtt rLambdaFunction.Arn

  rLambdaFunctionAliasErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Sub ${rLambdaFunction}:${pFunctionAliasName}
        - Name: FunctionName
          Value: !Ref rLambdaFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 0

  rLambdaFunctionVersionErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Lambda Function Error > 0
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: Resource
          Value: !Ref rLambdaFunction.Version
        - Name: FunctionName
          Value: !Ref rLambdaFunction
      EvaluationPeriods: 1
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 300
      Statistic: Sum
      Threshold: 0

Outputs:
  LambdaFunction:
    Description: Lambda function Alias
    Value: !Ref rLambdaFunction.Alias

  LambdaFunctionSSMParameter:
    Description: Lambda function Arn
    Value: !Ref rLambdaArnSSMParameter
